import os, sys

missing_apilist = [
           "https://%s/api/network/default_gateway",
           "https://%s/api/network/dns",
           "https://%s/api/network/hostname",
           "https://%s/api/network/interfaces/vips",
           "https://%s/api/clusters",
           "https://%s/api/ha",
           "https://%s/api/ha/backup",
           "https://%s/api/ha/dead_time",
 	   "https://%s/api/ha/heartbeat_start",
	   "https://%s/api/ha/heartbeat_status",
	   "https://%s/api/ha/heartbeat_stop",
	   "https://%s/api/ha/init_dead_time",
	   "https://%s/api/ha/keep_alive_time",
	   "https://%s/api/ha/sqlite_data",
	   "https://%s/api/ha/start_rsync",
	   "https://%s/api/ha/status",
           "https://%s/api/ha/stop_rsync",
           "https://%s/api/ha/warn_time",
           "https://%s/api/system/backup",
	   "https://%s/api/system/date",
           "https://%s/api/system/service/list",
           "https://%s/api/system/timezone",
           "https://%s/api/system/timezone_list",
           "https://%s/api/system/uptime",
           "https://%s/api/permissions",
           "https://%s/api/iscloud/status",
           "https://%s/api/tcpdump/list",
           "https://%s/api/system/analytics",
           "https://%s/api/system/loadbalancer"
           "https://%s/api/system/loadbalancer/version",
           ]
invalid_apilist = [
          "https://%s/api//cluster/2/logs_level",
          "https://%s/api//cluster/2/firewall_status",
          "https://%s/api//cluster/2/firewall_rules",
          "https://%s/api//cluster/2/database/1/firewall_rule/1",
          "https://%s/api//cluster/2/logs",
          "https://%s/api//cluster/2/logs_backup",
          "https://%s/api//cluster/2/logs_level",
          "https://%s/api//cluster/2/logs_slow_query",
          "https://%s/api//cluster/2/cache_cleanup_cycle_time",
          "https://%s/api//cluster/2/cache_empty_result_state",
          "https://%s//api/cluster/2/cache_limit",
          "https://%s/api//cluster/2/cache_manager/schedule",
          "https://%s/api//cluster/2/cache_manager/schedule",
          "https://%s/api//cluster/2/cache_manager/schedule/delete_for_database/1",
          "https://%s/api//cluster/2/cache_manager/schedule/delete_for_database/1/pattern/1",
          "https://%s/api//cluster/2/cache_rules",
          "https://%s/api//cluster/2/cache_rules/export_cache_csv",
          "https://%s/api//cluster/2/cluster_analytics",
          "https://%s/api//cluster/2/database/1/cache_rule/1",
          "https://%s/api//cluster/2/database/1/precache_pattern/1",
          "https://%s/api//cluster/2/database/1/storedprocedure_rule/1",
          "https://%s/api//cluster/2/advanced_settings",
          "https://%s/api//cluster/2/advanced_settings/defaults",
          "https://%s/api//cluster/2/sharding",
          "https://%s/api//cluster/2/sharding/rule/1",
          "https://%s/api//cluster/2/acl_rule",
          "https://%s/api//cluster/2/acl_rule/1",
          "https://%s/api//cluster/2/acl_rule/1",
          "https://%s/api//cluster/2/acl_rules",
          ]

if __name__ == '__main__':
    print missing_apilist
    print invalid_apilist 
