#!/usr/bin/python

#
# Copyright (c) 2012, ScalArc Inc.
# All Rights Reserved
#

import sys
try:
    import idb.cmd.health_monitor.health_monitor as health_monitor
    health_monitor.main()
except ImportError as exc:
    print >>sys.stderr, "Failed to load modules %",exc
